/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef } from "react";
import { Search, History, Download, ChevronDown, ChevronUp, Loader2, Microscope, AlertCircle, Trash2, Copy, FileText } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import Markdown from "react-markdown";
import { fetchMicrobeData, MicrobeData } from "./services/geminiService";
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const RECENT_SEARCHES_KEY = "microbecheck_recent_searches";

export default function App() {
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<MicrobeData | null>(null);
  const [recentSearches, setRecentSearches] = useState<string[]>([]);
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({});
  const resultRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const saved = localStorage.getItem(RECENT_SEARCHES_KEY);
    if (saved) {
      setRecentSearches(JSON.parse(saved));
    }
  }, []);

  const saveSearch = (name: string) => {
    const updated = [name, ...recentSearches.filter(s => s !== name)].slice(0, 5);
    setRecentSearches(updated);
    localStorage.setItem(RECENT_SEARCHES_KEY, JSON.stringify(updated));
  };

  const handleSearch = async (searchQuery: string) => {
    if (!searchQuery.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const data = await fetchMicrobeData(searchQuery);
      setResult(data);
      saveSearch(data.name);
      // Expand first section by default
      if (data.sections.length > 0) {
        setExpandedSections({ [data.sections[0].title]: true });
      }
    } catch (err) {
      console.error(err);
      setError("Failed to fetch microbe data. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const toggleSection = (title: string) => {
    setExpandedSections(prev => ({
      ...prev,
      [title]: !prev[title]
    }));
  };

  const exportToMarkdown = () => {
    if (!result) return;
    
    let content = `# ${result.name} (${result.type})\n\n`;
    content += `*Generated by MicrobeCheck - FRCPath High-Yield Reference*\n\n`;
    
    result.sections.forEach(section => {
      content += `## ${section.title}\n\n${section.content}\n\n`;
    });
    
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `MicrobeCheck_${result.name.replace(/\s+/g, "_")}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = () => {
    if (!result) return;
    
    let content = `${result.name} (${result.type})\n\n`;
    result.sections.forEach(section => {
      content += `${section.title}\n${section.content}\n\n`;
    });

    navigator.clipboard.writeText(content).then(() => {
      alert("Reference copied to clipboard!");
    }).catch(err => {
      console.error("Failed to copy: ", err);
    });
  };

  const clearRecent = () => {
    setRecentSearches([]);
    localStorage.removeItem(RECENT_SEARCHES_KEY);
  };

  return (
    <div className="min-h-screen bg-[#0f172a] text-slate-200 selection:bg-medical-teal/30">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-[#0f172a]/80 backdrop-blur-md border-b border-slate-800">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-medical-teal/10 rounded-lg">
              <Microscope className="w-6 h-6 text-medical-teal" />
            </div>
            <h1 className="text-xl font-bold tracking-tight text-white">
              Microbe<span className="text-medical-teal">Check</span>
            </h1>
          </div>
          <div className="text-xs font-mono text-slate-500 hidden sm:block">
            FRCPath Reference v1.0
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-8 space-y-8">
        {/* Search Section */}
        <section className="space-y-4">
          <div className="relative group">
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSearch(query)}
              placeholder="Search organism (e.g. S. aureus, CMV, Aspergillus)..."
              className="w-full bg-slate-900/50 border border-slate-700 rounded-2xl py-4 pl-12 pr-4 focus:outline-none focus:ring-2 focus:ring-medical-teal/50 focus:border-medical-teal transition-all placeholder:text-slate-500 text-lg"
            />
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-500 group-focus-within:text-medical-teal transition-colors" />
            <button
              onClick={() => handleSearch(query)}
              disabled={loading || !query.trim()}
              className="absolute right-2 top-1/2 -translate-y-1/2 bg-medical-teal hover:bg-medical-teal-dark disabled:opacity-50 disabled:cursor-not-allowed text-white px-6 py-2 rounded-xl font-medium transition-all shadow-lg shadow-medical-teal/20"
            >
              {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : "Search"}
            </button>
          </div>

          {/* Recent Searches */}
          {recentSearches.length > 0 && (
            <div className="flex flex-wrap items-center gap-2 pt-2">
              <div className="flex items-center gap-1 text-xs font-semibold text-slate-500 uppercase tracking-wider mr-2">
                <History className="w-3 h-3" />
                Recent
              </div>
              {recentSearches.map((s) => (
                <button
                  key={s}
                  onClick={() => {
                    setQuery(s);
                    handleSearch(s);
                  }}
                  className="px-3 py-1 bg-slate-800/50 hover:bg-slate-700 border border-slate-700 rounded-full text-sm text-slate-300 transition-colors"
                >
                  {s}
                </button>
              ))}
              <button 
                onClick={clearRecent}
                className="p-1 text-slate-500 hover:text-red-400 transition-colors"
                title="Clear history"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          )}
        </section>

        {/* Error State */}
        <AnimatePresence>
          {error && (
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl flex items-center gap-3 text-red-400"
            >
              <AlertCircle className="w-5 h-5 shrink-0" />
              <p className="text-sm">{error}</p>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Loading State */}
        {loading && (
          <div className="py-20 flex flex-col items-center justify-center space-y-4">
            <div className="relative">
              <div className="w-16 h-16 border-4 border-medical-teal/20 border-t-medical-teal rounded-full animate-spin"></div>
              <Microscope className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-6 h-6 text-medical-teal" />
            </div>
            <div className="text-center">
              <p className="text-lg font-medium text-white">Synthesizing Clinical Data...</p>
              <p className="text-sm text-slate-500">Consulting UK SMIs, EUCAST & PubMed</p>
            </div>
          </div>
        )}

        {/* Results Section */}
        {result && !loading && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-6"
          >
            <div className="flex items-end justify-between border-b border-slate-800 pb-4">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className={cn(
                    "px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-widest",
                    result.type === "Bacteria" && "bg-blue-500/20 text-blue-400",
                    result.type === "Virus" && "bg-purple-500/20 text-purple-400",
                    result.type === "Fungus" && "bg-orange-500/20 text-orange-400",
                    result.type === "Parasite" && "bg-green-500/20 text-green-400"
                  )}>
                    {result.type}
                  </span>
                </div>
                <h2 className="text-3xl font-bold text-white italic">{result.name}</h2>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={copyToClipboard}
                  className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-xl text-sm font-medium transition-colors"
                  title="Copy to clipboard"
                >
                  <Copy className="w-4 h-4" />
                  <span className="hidden sm:inline">Copy</span>
                </button>
                <button
                  onClick={exportToMarkdown}
                  className="flex items-center gap-2 px-4 py-2 bg-medical-teal/10 hover:bg-medical-teal/20 border border-medical-teal/30 rounded-xl text-sm font-medium text-medical-teal transition-colors"
                  title="Download as Markdown"
                >
                  <FileText className="w-4 h-4" />
                  <span className="hidden sm:inline">Download (.md)</span>
                </button>
              </div>
            </div>

            <div ref={resultRef} className="space-y-4 p-1">
              {result.sections.map((section) => (
                <div
                  key={section.title}
                  className="bg-slate-900/40 border border-slate-800 rounded-2xl overflow-hidden"
                >
                  <button
                    onClick={() => toggleSection(section.title)}
                    className="w-full px-6 py-4 flex items-center justify-between hover:bg-slate-800/50 transition-colors text-left"
                  >
                    <span className="font-semibold text-slate-200">{section.title}</span>
                    {expandedSections[section.title] ? (
                      <ChevronUp className="w-5 h-5 text-medical-teal" />
                    ) : (
                      <ChevronDown className="w-5 h-5 text-slate-500" />
                    )}
                  </button>
                  <AnimatePresence>
                    {expandedSections[section.title] && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.2 }}
                      >
                        <div className="px-6 pb-6 pt-2 border-t border-slate-800/50">
                          <div className="markdown-body text-sm text-slate-300">
                            <Markdown>{section.content}</Markdown>
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              ))}
            </div>

            <footer className="pt-8 text-center text-xs text-slate-600 space-y-2">
              <p>© 2026 MicrobeCheck • FRCPath High-Yield Reference</p>
              <p>Data synthesized from UK SMIs, EUCAST, ClinMicroNow & Peer-reviewed literature.</p>
              <p className="italic">Disclaimer: For educational purposes only. Always consult local trust guidelines for clinical decisions.</p>
            </footer>
          </motion.div>
        )}

        {/* Empty State */}
        {!result && !loading && !error && (
          <div className="py-20 text-center space-y-6">
            <div className="inline-flex p-6 bg-slate-900/50 rounded-full border border-slate-800">
              <Microscope className="w-12 h-12 text-slate-700" />
            </div>
            <div className="max-w-md mx-auto space-y-2">
              <h3 className="text-xl font-semibold text-white">Ready for Analysis</h3>
              <p className="text-slate-500">
                Enter any bacterium, virus, fungus, or parasite to get high-yield clinical and laboratory insights.
              </p>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 max-w-2xl mx-auto pt-4">
              {["S. aureus", "C. difficile", "HIV-1", "C. albicans"].map(ex => (
                <button
                  key={ex}
                  onClick={() => {
                    setQuery(ex);
                    handleSearch(ex);
                  }}
                  className="p-3 bg-slate-900/30 border border-slate-800 rounded-xl text-xs text-slate-400 hover:border-medical-teal/50 hover:text-medical-teal transition-all"
                >
                  Try "{ex}"
                </button>
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
